### ISSUE TITLE
z-index of confetti

### ISSUE THREAD

**Issue by Sejori** [mathusummut/confetti.js#2]
Hi there, love this!

A problem I have is that the confetti is rendering behind all other content on my page. Can I adjust the z-index easily?

**Comment by Sejori** [comment]
Actually, it's not the z-index. The confetti canvas was just rendering below all other content. 

Fixed with following:

`			canvas.setAttribute("style", "display:block;z-index:999999;pointer-events:none;position:absolute;top:0;");`

**Comment by mathusummut** [comment]
Thanks! I have added the fix to the code, have a nice day.
