### ISSUE TITLE
how to use this with React?

### ISSUE THREAD

**Issue by DevNM21** [mathusummut/confetti.js#9]

**Comment by Bergrebell** [comment]
@DevNM21 - I don't know about react but i just used it in VueJS and it should be similar in react.

1. download and save `confetti.js` from this repository to `/lib/confettig.js` in your vue-project.
2. add `export default confetti` at the bottom of `/lib/confettig.js`
3. import it inside your component via `import confetti from '@/lib/confetti.js'`
4. use it as described in the docs (`confetti.start()`)

**Comment by DevNM21** [comment]
Thanks!

**Comment by DevNM21** [comment]
Thanks for the help! I'll try that out, but this worked for me as well: 
`  componentDidMount() {
        const script = document.createElement("script");
        script.src = "https://cdn.jsdelivr.net/gh/mathusummut/confetti.js/confetti.min.js";
        script.async = true;
        document.body.appendChild(script);
    }
`
then calling it  like : 
`        window.confetti.start()
`
